### ISSUE TITLE
Argument 2 passed to API::showUIbyID() must be type integer, null given.

### ISSUE THREAD

**Issue by TommoVirtualReality** [thebigsmileXD/customui#8]
This was called in TestCustomSubCommand.php

**Comment by TommoVirtualReality** [comment]
Any assistance @thebigsmileXD ?

**Comment by TommoVirtualReality** [comment]
@thebigsmileXD how do I fix this error? pls help :(

**Comment by thebigsmileXD** [comment]
This is the last warning. If you continue to spam in issue trackers i am active in or owner of, you get banned.

To the issue:
https://github.com/thebigsmileXD/customui/blob/master/examples/customuitest/src/xenialdan/customuitest/subcommand/TestCustomSubCommand.php#L41
`Loader::$uis['customUI']` - contains the id
https://github.com/thebigsmileXD/customui/blob/master/examples/customuitest/src/xenialdan/customuitest/Loader.php#L26 - is the variable - empty so far
https://github.com/thebigsmileXD/customui/blob/master/examples/customuitest/src/xenialdan/customuitest/Loader.php#L58 - defines the id.

This issue is invalid.

**Comment by TommoVirtualReality** [comment]
Please test it yourself @thebigsmileXD - it says ID must be int.. idk :/

**Comment by thebigsmileXD** [comment]
It is checked. Works.
